version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-service
    ports:
      - "6831:6831/udp"   # Jaeger Agent UDP port (for legacy protocol)
      - "16686:16686"     # Jaeger UI
      - "4318:4318"       # Jaeger OTLP HTTP endpoint (internal)

  jaeger-cors-proxy:
    image: nginx:alpine
    container_name: jaeger-cors-proxy
    ports:
      - "4319:80"        # Expose the proxy on port 4319 on the host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - jaeger
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"      # Prometheus UI available at http://localhost:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411" 