global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']
  - job_name: 'rr-app-server'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.2.12:3000'] 
